# Generated by Django 3.0.1 on 2019-12-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
                ('ava', models.CharField(max_length=250)),
                ('ref', models.CharField(max_length=30, unique=True)),
                ('article_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('games_ids', models.CharField(max_length=250)),
            ],
        ),
    ]
